const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Physics,
		C3.Behaviors.Tween,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.IID,
		C3.Behaviors.Physics.Acts.SetCollisionFilter,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Physics.Exps.VelocityX,
		C3.Behaviors.Physics.Exps.VelocityY,
		C3.Behaviors.Physics.Cnds.IsEnabled,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Exps.dt,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Browser.Acts.GoToURLWindow
	];
};
self.C3_JsPropNameTable = [
	{Physics: 0},
	{can: 0},
	{flooor: 0},
	{Z_Height: 0},
	{Z_Velocity: 0},
	{IsThrown: 0},
	{Tween: 0},
	{ball: 0},
	{Touch: 0},
	{Sprite2: 0},
	{bg: 0},
	{arrow: 0},
	{popup: 0},
	{hand: 0},
	{flipck: 0},
	{NROGOLDLOGO: 0},
	{final: 0},
	{Browser: 0},
	{IsDragging: 0},
	{StartX: 0},
	{chances: 0},
	{StartY: 0},
	{Score: 0},
	{tmp: 0},
	{gravity: 0},
	{wakeup: 0}
];

self.InstanceType = {
	can: class extends self.ISpriteInstance {},
	flooor: class extends self.ISpriteInstance {},
	ball: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	bg: class extends self.ISpriteInstance {},
	arrow: class extends self.ISpriteInstance {},
	popup: class extends self.ISpriteInstance {},
	hand: class extends self.ISpriteInstance {},
	flipck: class extends self.ISpriteInstance {},
	NROGOLDLOGO: class extends self.ISpriteInstance {},
	final: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {}
}