const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Rotate,
		C3.Behaviors.Pin,
		C3.Behaviors.Physics,
		C3.Behaviors.Bullet,
		C3.Behaviors.Tween,
		C3.Plugins.Touch,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Plugins.Browser,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Pin.Acts.Unpin,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Cnds.PickByHighestLowestValue,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Browser.Acts.GoToURLWindow
	];
};
self.C3_JsPropNameTable = [
	{Rotate: 0},
	{wheel: 0},
	{Pin: 0},
	{Physics: 0},
	{lowhealth: 0},
	{randomspawn: 0},
	{enemySwarm: 0},
	{toughlevel: 0},
	{lowscore: 0},
	{bossfight: 0},
	{timelimit: 0},
	{limitedLives: 0},
	{Bullet: 0},
	{Tween: 0},
	{oilDrop: 0},
	{Touch: 0},
	{gameStress: 0},
	{dropletCount: 0},
	{dropletCount2: 0},
	{bg: 0},
	{bottle: 0},
	{screen1Headline: 0},
	{Sine: 0},
	{tapForSoothingReliel: 0},
	{Text: 0},
	{popup: 0},
	{Browser: 0},
	{drops: 0},
	{timuu: 0}
];

self.InstanceType = {
	wheel: class extends self.ISpriteInstance {},
	lowhealth: class extends self.ISpriteInstance {},
	randomspawn: class extends self.ISpriteInstance {},
	enemySwarm: class extends self.ISpriteInstance {},
	toughlevel: class extends self.ISpriteInstance {},
	lowscore: class extends self.ISpriteInstance {},
	bossfight: class extends self.ISpriteInstance {},
	timelimit: class extends self.ISpriteInstance {},
	limitedLives: class extends self.ISpriteInstance {},
	oilDrop: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	gameStress: class extends self.ISpriteInstance {},
	dropletCount: class extends self.ISpriteInstance {},
	dropletCount2: class extends self.ISpriteInstance {},
	bg: class extends self.ISpriteInstance {},
	bottle: class extends self.ISpriteInstance {},
	screen1Headline: class extends self.ISpriteInstance {},
	tapForSoothingReliel: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	popup: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {}
}